version: "3"

services:
  rmfweb-email-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: rmfweb-email-api
    container_name: rmfweb-email-api
    ports:
      - "3030:3000"
    volumes:
      - ./src:/home/docker/rmfweb-email-api/app/src
    restart: unless-stopped